sudo: false
dist: trusty
language: node_js
node_js:
  - '7.0.0'
branches:
    only:
      - master
before_script:
- npm install -g --silent firebase-tools
- npm install -g @angular/cli
- npm install
- ng build
after_success:
 - firebase deploy --token $FIREBASE_TOKEN 
